```{r, warning=FALSE}
library(shiny)
library(shinythemes)
library(gtools)
library(Rcpp)
```


```{r, warning=FALSE}
# Fonction pour générer une ligne valide
generate_valid_row <- function(taille) {
  vec <- rep(0, taille)
  i <- 1
  j <- 0
  while (i < (taille + 1)) {
    j <- j + 1
    if (j == 2) {
      t <- vec[i - 1] + vec[i]
      j <- 0
      if (t == 0) {
        vec[i] <- 1
      } else if (t == 2) {
        vec[i] <- 0
      }
    } else {
      vec[i] <- sample(c(0, 1), 1, prob = c(0.5, 0.5))
    }
    i <- i + 1
  }
  return(vec)
}

# Fonction de génération de la matrice
generate_valid_matrix <- function(taille) {
  q <- taille - 1
  x <- generate_valid_row(taille)
  init_mat <- matrix(c(x, rep(0,taille*q)), nrow = taille, ncol = taille)
  
  for (i in 1:q) {
    init_mat[,i+1] = rotate_vector((x,i))
  }
  return(init_mat)
}

# Créer la matrice de jeu en fonction de la difficulté
creer_matrice_takuzu <- function(matrice_base, difficulte = "facile") {
  grid <- matrice_base
  nrow_grid <- nrow(grid)
  ncol_grid <- ncol(grid)
  prob_na <- switch(difficulte,
                    "facile" = 0.10,
                    "avancee" = 0.25,
                    "difficile" = 0.35,
                    stop("Difficulté non reconnue"))
  
  for (i in 1:nrow_grid) {
    for (j in 1:ncol_grid) {
      if (runif(1) < prob_na) {
        grid[i, j] <- NA
      }
    }
  }
  return(grid)
}


```




```{r, warning=FALSE}
# Ajuster les indices en fonction des erreurs du joueur
ajuster_indices_takuzu <- function(matrice_base, matrice_premplie) {
  grid <- matrice_premplie
  nrow_grid <- nrow(grid)
  ncol_grid <- ncol(grid)
  
  for (i in 1:nrow_grid) {
    for (j in 1:ncol_grid) {
      if (is.na(grid[i, j])) {
        grid[i, j] <- matrice_base[i, j]
      }
    }
  }
  return(grid)
}

# Vérifier si la grille est valide
verifier_grille <- function(grid, size) {
  valid <- all(rowSums(!is.na(grid) & grid == 1, na.rm = TRUE) == size / 2) && 
           all(colSums(!is.na(grid) & grid == 1, na.rm = TRUE) == size / 2)
  return(valid)
}


```




```{r, warning=FALSE}
# UI de l'application
ui <- fluidPage(
  theme = shinytheme("superhero"),
  tags$head(
    tags$style(HTML("
      /* Conteneur principal centré pour grille + boutons */
      .grid-and-buttons {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 20px;
      }

      /* Capsule rouge autour de la grille */
      .red-capsule {
        border: 5px solid red;
        background-color: #FFCDD2;  /* Rouge clair */
        padding: 20px;
        display: inline-block;
        border-radius: 20px;  /* Coins arrondis */
        box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.3);
        margin-bottom: 10px;
      }

      /* Capsule externe autour de la grille et des boutons */
      .outer-capsule-container {
        border: 5px solid #FFD700;  /* Jaune */
        background-color: #F5F5DC;
        padding: 30px;
        display: inline-block;
        border-radius: 30px;
        box-shadow: 0px 12px 20px rgba(0, 0, 0, 0.3);
        margin-bottom: 20px;
      }

      /* Capsule jaune avec effet 3D sans perspective */
      .outer-capsule-container {
        border: 5px solid #FFD700;
        background-color: #F5F5DC;
        padding: 30px;
        display: inline-block;
        border-radius: 30px;
        box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.4);  /* Ombre plus marquée */
        transform: translateY(5px);  /* Simule l'élévation de la capsule */
        transition: all 0.3s ease;
      }

      .outer-capsule-container:hover {
        box-shadow: 0px 15px 30px rgba(0, 0, 0, 0.5);  /* Ombre plus marquée au survol */
        transform: translateY(10px);  /* Effet d'élévation encore plus accentué */
      }

      /* Conteneur de la grille */
      .grid-container {
        margin-bottom: 20px;
      }

      /* Conteneur des boutons */
      .button-container {
        display: flex;
        justify-content: center;
        gap: 15px;
        padding: 10px;
        background-color: #546E7A;
        border-radius: 10px;
        box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.15);
      }

      /* Style des boutons Takuzu */
      .takuzu-btn { 
        background-color: #37474F;
        border-radius: 50%; 
        border: 1px solid white; 
        width: 50px; 
        height: 50px; 
        color: white; 
        font-size: 20px; 
        text-align: center; 
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        transition: all 0.2s ease-in-out;
      }
      .takuzu-btn-1 { background-color: #FFA500; }  /* Orange pour 1 */
      .takuzu-btn-0 { background-color: #4CAF50; }  /* Vert pour 0 */
      .takuzu-btn:hover { 
        background-color: #FFA000;
        box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.2);
        transform: translateY(-3px); 
      }

      /* Boutons d'action */
      .new-grid-btn, .check-grid-btn, .hint-btn {
        background-color: #0288D1;
        border-color: #01579B;
        color: white;
        font-size: 16px;
        padding: 10px 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        transition: all 0.2s ease-in-out;
      }

      .new-grid-btn:hover { background-color: #01579B; transform: translateY(-3px); }
      .check-grid-btn:hover { background-color: #C62828; transform: translateY(-3px); }
      .hint-btn:hover { background-color: #FFD700; transform: translateY(-3px); color: black; }

      /* Animation du message de statut clignotant */
      .status-message {
        font-weight: bold;
        font-size: 18px;
        text-align: center;
        color: white;
        animation: pulse 1.5s infinite;
      }
      @keyframes pulse {
        0% { color: white; }
        50% { color: #FFD700; }
        100% { color: white; }
      }

      /* Message de Réfléchissez encore 30 secondes */
      .think-message {
        color: red;
        font-size: 24px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 20px;
      }

      /* Style des émojis dans la capsule à fond blanc */
      .emoji-container {
        font-size: 30px;
        text-align: center;
        margin-bottom: 20px;
      }
    "))
  ),
  titlePanel("Jeu Takuzu"),
  tabsetPanel(
    tabPanel("Jeu",
             sidebarLayout(
               sidebarPanel(
                 sliderInput("gridSize", "Taille de la grille :", 
                             min = 8, max = 12, value = 8, step = 2,
                             animate = TRUE),
                 selectInput("difficulty", "Choisir la difficulté :", 
                             choices = c("Facile" = "facile", 
                                         "Avancée" = "avancee", 
                                         "Difficile" = "difficile"), 
                             selected = "facile"),
                 verbatimTextOutput("status")
               ),
               mainPanel(
                 div(class = "outer-capsule-container",  # Capsule externe autour de grille et boutons
                     div(class = "grid-and-buttons",
                         div(class = "think-message", textOutput("thinkMessage")),  
                         
                         # Capsule à fond blanc contenant les emojis
                         div(class = "emoji-container", "😊 😀 😁"),  # Émojis jaunes
                         
                         div(class = "red-capsule",  
                             div(class = "grid-container", uiOutput("gridUI"))
                         ),
                         
                         div(class = "button-container",
                             actionButton("reset", "Nouvelle Grille", class = "new-grid-btn"),
                             actionButton("check", "Vérifier la Grille", class = "check-grid-btn"),
                             actionButton("hint", "Obtenir un Indice", class = "hint-btn"),
                             actionButton("result", "Résultat", class = "new-grid-btn")  
                         )
                     )
                 )
               )
             )
    ),
    tabPanel("Règles du Jeu",
             h3("Règles du Jeu Takuzu"),
             p("Le but du jeu Takuzu est de remplir la grille avec des 0 et des 1 de manière à respecter les règles suivantes :"),
             tags$ul(
               tags$li("Chaque ligne et chaque colonne doit contenir un nombre égal de 0 et de 1."),
               tags$li("Aucune ligne ni colonne ne peut contenir plus de deux 0 ou plus de deux 1 consécutifs."),
               tags$li("La grille ne doit pas contenir deux lignes ou deux colonnes identiques.")
             )
    )
  )
)



```




```{r, warning=FALSE}
server <- function(input, output, session) {
  
  size <- reactive({ input$gridSize })
  takuzu_grid <- reactiveVal()
  start_time <- reactiveVal(NULL)
  matrice_base <- reactiveVal()  
  resultat_affiche <- reactiveVal(FALSE)  
  
  observe({
    base_grid <- generate_valid_matrix(input$gridSize)
    matrice_base(base_grid)
    takuzu_grid(creer_matrice_takuzu(base_grid, difficulte = input$difficulty))
    start_time(Sys.time())
    resultat_affiche(FALSE)
  })
  
  # Affichage de la grille
  output$gridUI <- renderUI({
    grid <- takuzu_grid()
    current_size <- size()
    buttons <- lapply(1:current_size, function(i) {
      fluidRow(
        lapply(1:current_size, function(j) {
          actionButton(paste0("btn_", i, "_", j), 
                       label = ifelse(is.na(grid[i, j]), "", grid[i, j]), 
                       class = paste("takuzu-btn", 
                                     ifelse(grid[i, j] == 1, "takuzu-btn-1", 
                                            ifelse(grid[i, j] == 0, "takuzu-btn-0", ""))))
        })
      )
    })
    do.call(tagList, buttons)
  })
  
  # Interaction avec les boutons
  observe({
    current_size <- size()
    for (i in 1:current_size) {
      for (j in 1:current_size) {
        local({
          ii <- i; jj <- j
          btn_id <- paste0("btn_", ii, "_", jj)
          
          observeEvent(input[[btn_id]], {
            if (!resultat_affiche()) {
              grid <- takuzu_grid()
              current_value <- grid[ii, jj]
              new_value <- ifelse(is.na(current_value), 0, ifelse(current_value == 0, 1, NA))
              grid[ii, jj] <- new_value
              takuzu_grid(grid)
              updateActionButton(session, btn_id, label = ifelse(is.na(new_value), "", new_value))
            }
          }, ignoreNULL = FALSE)
        })
      }
    }
  })
  
  # Vérification de la grille
  observeEvent(input$check, {
    grid <- takuzu_grid()
    valid <- verifier_grille(grid, size())
    
    output$status <- renderText({
      if (valid) "✅ Grille Valide !" else "❌ Il y a des erreurs dans la grille."
    })
  })
  
  # Nouvelle grille
  observeEvent(input$reset, {
    if (!resultat_affiche()) {
      base_grid <- matrice_base()
      takuzu_grid(creer_matrice_takuzu(base_grid, difficulte = input$difficulty))
    }
  })
  
  # Indices
  observeEvent(input$hint, {
    if (!resultat_affiche()) {
      grid <- takuzu_grid()
      base_grid <- matrice_base()
      
      updated_grid <- ajuster_indices_takuzu(base_grid, grid)
      takuzu_grid(updated_grid)
      
      for (i in 1:nrow(updated_grid)) {
        for (j in 1:ncol(updated_grid)) {
          updateActionButton(session, paste0("btn_", i, "_", j), label = ifelse(is.na(updated_grid[i, j]), "", updated_grid[i, j]))
        }
      }
      
      # Afficher le message d'indication et le faire disparaître après 6 secondes
      output$hintMessage <- renderText("Voici un indice!")
      Sys.sleep(6)  # Attendre 6 secondes
      output$hintMessage <- renderText("")  # Effacer le message
    }
  })
  
  # Afficher le résultat après 3 minutes
  observeEvent(input$result, {
    if (is.null(start_time()) || difftime(Sys.time(), start_time(), units = "mins") >= 3) {
      resultat_affiche(TRUE)
      output$status <- renderText({ "⏱ Temps écoulé! Voici la solution:" })
      grid_solution <- matrice_base() 
      takuzu_grid(grid_solution)  # Affiche la solution
    }
    
    # Afficher le message de réflexion et le faire disparaître après 6 secondes
    output$thinkMessage <- renderText("Réfléchissez encore 30 secondes!")
    Sys.sleep(6)  # Attendre 6 secondes
    output$thinkMessage <- renderText("")  # Effacer le message
  })
}

shinyApp(ui = ui, server = server)


```




```{r, warning=FALSE}


```




```{r, warning=FALSE}


```




```{r, warning=FALSE}


```




```{r, warning=FALSE}


```




