---
title: "Projet: Takuzu"
author: "ATTOUMANI Ibrahim"
output: pdf_document
date: "19 fevrier 2025"
fontsize: 12pt
mainfont: "Times New Roman"
header-include:
  - usepackage{xcolor}
---

```{r, warning=FALSE}
library(shiny)
library(shinythemes)
library(gtools)
library(Rcpp)
```


Génération de la grille de base avec une autre page incluant les règles du jeux, les caractéristiques de l'interface avec les boutons stylisés et les fonctionnalités de validation. J'ai intégré le thème et les couleurs dans le style des boutons tout en maintenant l'originalité du design.

```{r, warning=FALSE}
# Fonction pour générer une grille Takuzu partiellement remplie
generate_takuzu_grid <- function(size = 8, fill_rate = 0.5) {
  grid <- matrix(sample(c(0, 1, NA), size * size, replace = TRUE, 
                        prob = c(fill_rate / 2, fill_rate / 2, 1 - fill_rate)), 
                 nrow = size, ncol = size)
  return(grid)
}

# Interface utilisateur
ui <- fluidPage(
  theme = shinytheme("superhero"),
  tags$head(
    tags$style(HTML("
      /* Conteneur principal centré pour grille + boutons */
      .grid-and-buttons {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 20px;
      }

      /* Conteneur de la grille */
      .grid-container {
        border: 5px solid #FFD700;
        background-color: #F5F5DC;
        padding: 20px;                
        display: inline-block;
        border-radius: 15px;
        box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.3);
        margin-bottom: 20px;
      }

      /* Conteneur des boutons */
      .button-container {
        display: flex;
        justify-content: center;
        gap: 15px;
        padding: 10px;
        background-color: #546E7A;
        border-radius: 10px;
        box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.15);
      }

      /* Style des boutons Takuzu */
      .takuzu-btn { 
        background-color: #37474F;
        border-radius: 50%; 
        border: 1px solid white; 
        width: 50px; 
        height: 50px; 
        color: white; 
        font-size: 20px; 
        text-align: center; 
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        transition: all 0.2s ease-in-out;
      }
      .takuzu-btn-1 { background-color: #FFA500; }  /* Orange pour 1 */
      .takuzu-btn-0 { background-color: #4CAF50; }  /* Vert pour 0 */
      .takuzu-btn:hover { 
        background-color: #FFA000;
        box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.2);
        transform: translateY(-3px); 
      }

      /* Boutons d'action */
      .new-grid-btn, .check-grid-btn, .hint-btn {
        background-color: #0288D1;
        border-color: #01579B;
        color: white;
        font-size: 16px;
        padding: 10px 20px;
        border-radius: 10px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        transition: all 0.2s ease-in-out;
      }

      .new-grid-btn:hover { background-color: #01579B; transform: translateY(-3px); }
      .check-grid-btn:hover { background-color: #C62828; transform: translateY(-3px); }
      .hint-btn:hover { background-color: #FFD700; transform: translateY(-3px); color: black; }

      /* Animation du message de statut clignotant */
      .status-message {
        font-weight: bold;
        font-size: 18px;
        text-align: center;
        color: white;
        animation: pulse 1.5s infinite;
      }
      @keyframes pulse {
        0% { color: white; }
        50% { color: #FFD700; }
        100% { color: white; }
      }

      /* Message de Réfléchissez encore 30 secondes */
      .think-message {
        color: red;
        font-size: 24px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 20px;
      }
    "))
  ),
  titlePanel("Jeu Takuzu"),
  tabsetPanel(
    tabPanel("Jeu",
             sidebarLayout(
               sidebarPanel(
                 sliderInput("gridSize", "Taille de la grille :", min = 8, max = 12, value = 8, step = 1),
                 verbatimTextOutput("status")
               ),
               mainPanel(
                 div(class = "grid-and-buttons",
                     div(class = "think-message", textOutput("thinkMessage")),  # Ajout du message
                     div(class = "grid-container", uiOutput("gridUI")),
                     div(class = "button-container",
                         actionButton("reset", "Nouvelle Grille", class = "new-grid-btn"),
                         actionButton("check", "Vérifier la Grille", class = "check-grid-btn"),
                         actionButton("hint", "Obtenir un Indice", class = "hint-btn"),
                         actionButton("result", "Résultat", class = "new-grid-btn")  # Ajout du bouton Résultat
                     )
                 )
               )
             )
    ),
    tabPanel("Règles du Jeu",
             h3("Règles du Jeu Takuzu"),
             p("Le but du jeu Takuzu est de remplir la grille avec des 0 et des 1 de manière à respecter les règles suivantes :"),
             tags$ul(
               tags$li("Chaque ligne et chaque colonne doit contenir un nombre égal de 0 et de 1."),
               tags$li("Aucune ligne ni colonne ne peut contenir plus de deux 0 ou plus de deux 1 consécutifs."),
               tags$li("La grille ne doit pas contenir deux lignes ou deux colonnes identiques.")
             )
    )
  )
)

# Serveur
server <- function(input, output, session) {
  
  size <- reactive({ input$gridSize })
  takuzu_grid <- reactiveVal()
  start_time <- reactiveVal(NULL)  # Variable pour enregistrer l'heure du démarrage
  
  observe({
    takuzu_grid(generate_takuzu_grid(size()))
    start_time(Sys.time())  # Enregistrer le temps de démarrage
  })

  output$gridUI <- renderUI({
    grid <- takuzu_grid()
    current_size <- size()
    buttons <- lapply(1:current_size, function(i) {
      fluidRow(
        lapply(1:current_size, function(j) {
          actionButton(paste0("btn_", i, "_", j), 
                       label = ifelse(is.na(grid[i, j]), "", grid[i, j]), 
                       class = paste("takuzu-btn", 
                                     ifelse(grid[i, j] == 1, "takuzu-btn-1", 
                                            ifelse(grid[i, j] == 0, "takuzu-btn-0", ""))))
        })
      )
    })
    do.call(tagList, buttons)
  })

  observe({
    current_size <- size()
    for (i in 1:current_size) {
      for (j in 1:current_size) {
        local({
          ii <- i; jj <- j
          btn_id <- paste0("btn_", ii, "_", jj)
          
          observeEvent(input[[btn_id]], {
            grid <- takuzu_grid()
            current_value <- grid[ii, jj]
            new_value <- ifelse(is.na(current_value), 0, ifelse(current_value == 0, 1, NA))
            grid[ii, jj] <- new_value
            takuzu_grid(grid)
            updateActionButton(session, btn_id, label = ifelse(is.na(new_value), "", new_value))
          }, ignoreNULL = FALSE)
        })
      }
    }
  })

  observeEvent(input$check, {
    grid <- takuzu_grid()
    valid <- all(rowSums(!is.na(grid) & grid == 1, na.rm = TRUE) == size() / 2) && 
             all(colSums(!is.na(grid) & grid == 1, na.rm = TRUE) == size() / 2)
    
    output$status <- renderText({
      if (valid) "✅ Grille Valide !" else "❌ Il y a des erreurs dans la grille."
    })
  })

  observeEvent(input$reset, {
    takuzu_grid(generate_takuzu_grid(size()))
  })

  observeEvent(input$hint, {
    grid <- takuzu_grid()
    for (i in 1:nrow(grid)) {
      for (j in 1:ncol(grid)) {
        if (is.na(grid[i, j])) {
          grid[i, j] <- ifelse(runif(1) > 0.5, 1, 0)
          takuzu_grid(grid)
          updateActionButton(session, paste0("btn_", i, "_", j), label = grid[i, j])
          break
        }
      }
    }
  })

  observeEvent(input$result, {
    # Vérifier le temps écoulé
    if (difftime(Sys.time(), start_time(), units = "secs") < 30) {
      output$thinkMessage <- renderText("Réfléchissez encore 30 secondes")
    } else {
      # Afficher la grille correctement remplie
      grid <- takuzu_grid()
      # Remplir la grille avec des 0 et 1 valides (ici, on suppose que la grille est correctement remplie)
      takuzu_grid(generate_takuzu_grid(size(), fill_rate = 1))
      output$thinkMessage <- renderText("")
    }
  })
}

shinyApp(ui, server)


```
